Supervisor.create!(first_name: "Sarah", last_name: "Baranski", email: "sarah@test.com", phone_number: "555-555-3242", password: "password")
Supervisor.create!(first_name: "Kevin", last_name: "Tracy", email: "kdawg@test.com", phone_number: "555-555-2957", password: "password")

Position.create!(title: "Equipment Facilitator", current_pay: 12, previous_pay: 12)
Position.create!(title: "Equipment Supervisor", current_pay: 12.50, previous_pay: 12)
Position.create!(title: "Shift Lead", current_pay: 13, previous_pay: 12)

Student.create!(first_name: "Anna", last_name: "Wong", email: "anna@test.com", phone_number: "555-5557896", password: "password", requested_hours: 20, position_id: 3)
Student.create!(first_name: "Rachel", last_name: "Baranski", email: "rachel@test.com", phone_number: "555-5553456", password: "password", requested_hours: 15, position_id: 2)
Student.create!(first_name: "Ryan", last_name: "Chapman", email: "ryan@test.com", phone_number: "555-555-4893", password: "password", requested_hours: 18, position_id: 1)

Semester.create!(supervisor_id: 1, start_date: DateTime.new(2020, 9, 1), end_date: DateTime.new(2020, 12, 16), name: "Fall 2020")
Semester.create!(supervisor_id: 2, start_date: DateTime.new(2021, 1, 11), end_date: DateTime.new(2021, 5, 1), name: "Spring 2021")

Shift.create!(semester_id: 1, day: "Monday", time: "morning", supervisor_id: 1, total_required_staff: 2)
Shift.create!(semester_id: 1, day: "Monday", time: "afternoon", supervisor_id: 1, total_required_staff: 2)
Shift.create!(semester_id: 1, day: "Monday", time: "evening", supervisor_id: 1, total_required_staff: 1)
Shift.create!(semester_id: 1, day: "Tuesday", time: "morning", supervisor_id: 1, total_required_staff: 2)
Shift.create!(semester_id: 1, day: "Tuesday", time: "afternoon", supervisor_id: 1, total_required_staff: 2)
Shift.create!(semester_id: 1, day: "Tuesday", time: "evening", supervisor_id: 1, total_required_staff: 1)
Shift.create!(semester_id: 1, day: "Wednesday", time: "morning", supervisor_id: 1, total_required_staff: 2)
Shift.create!(semester_id: 1, day: "Wednesday", time: "afternoon", supervisor_id: 1, total_required_staff: 2)
Shift.create!(semester_id: 1, day: "Wednesday", time: "evening", supervisor_id: 1, total_required_staff: 1)
Shift.create!(semester_id: 1, day: "Thursday", time: "morning", supervisor_id: 1, total_required_staff: 2)
Shift.create!(semester_id: 1, day: "Thursday", time: "afternoon", supervisor_id: 1, total_required_staff: 2)
Shift.create!(semester_id: 1, day: "Thursday", time: "evening", supervisor_id: 1, total_required_staff: 1)
Shift.create!(semester_id: 1, day: "Friday", time: "morning", supervisor_id: 1, total_required_staff: 2)
Shift.create!(semester_id: 1, day: "Friday", time: "afternoon", supervisor_id: 1, total_required_staff: 2)
Shift.create!(semester_id: 1, day: "Friday", time: "evening", supervisor_id: 1, total_required_staff: 0)
Shift.create!(semester_id: 1, day: "Saturday", time: "morning", supervisor_id: 1, total_required_staff: 0)
Shift.create!(semester_id: 1, day: "Saturday", time: "afternoon", supervisor_id: 1, total_required_staff: 2)
Shift.create!(semester_id: 1, day: "Saturday", time: "evening", supervisor_id: 1, total_required_staff: 1)
Shift.create!(semester_id: 1, day: "Sunday", time: "morning", supervisor_id: 1, total_required_staff: 0)
Shift.create!(semester_id: 1, day: "Sunday", time: "afternoon", supervisor_id: 1, total_required_staff: 2)
Shift.create!(semester_id: 1, day: "Sunday", time: "evening", supervisor_id: 1, total_required_staff: 2)

Shift.create!(semester_id: 2, day: "Monday", time: "morning", supervisor_id: 1, total_required_staff: 2)
Shift.create!(semester_id: 2, day: "Monday", time: "afternoon", supervisor_id: 1, total_required_staff: 2)
Shift.create!(semester_id: 2, day: "Monday", time: "evening", supervisor_id: 1, total_required_staff: 1)
Shift.create!(semester_id: 2, day: "Tuesday", time: "morning", supervisor_id: 1, total_required_staff: 2)
Shift.create!(semester_id: 2, day: "Tuesday", time: "afternoon", supervisor_id: 1, total_required_staff: 2)
Shift.create!(semester_id: 2, day: "Tuesday", time: "evening", supervisor_id: 1, total_required_staff: 1)
Shift.create!(semester_id: 2, day: "Wednesday", time: "morning", supervisor_id: 1, total_required_staff: 2)
Shift.create!(semester_id: 2, day: "Wednesday", time: "afternoon", supervisor_id: 1, total_required_staff: 2)
Shift.create!(semester_id: 2, day: "Wednesday", time: "evening", supervisor_id: 1, total_required_staff: 1)
Shift.create!(semester_id: 2, day: "Thursday", time: "morning", supervisor_id: 1, total_required_staff: 2)
Shift.create!(semester_id: 2, day: "Thursday", time: "afternoon", supervisor_id: 1, total_required_staff: 2)
Shift.create!(semester_id: 2, day: "Thursday", time: "evening", supervisor_id: 1, total_required_staff: 1)
Shift.create!(semester_id: 2, day: "Friday", time: "morning", supervisor_id: 1, total_required_staff: 2)
Shift.create!(semester_id: 2, day: "Friday", time: "afternoon", supervisor_id: 1, total_required_staff: 2)
Shift.create!(semester_id: 2, day: "Friday", time: "evening", supervisor_id: 1, total_required_staff: 0)
Shift.create!(semester_id: 2, day: "Saturday", time: "morning", supervisor_id: 1, total_required_staff: 0)
Shift.create!(semester_id: 2, day: "Saturday", time: "afternoon", supervisor_id: 1, total_required_staff: 2)
Shift.create!(semester_id: 2, day: "Saturday", time: "evening", supervisor_id: 1, total_required_staff: 1)
Shift.create!(semester_id: 2, day: "Sunday", time: "morning", supervisor_id: 1, total_required_staff: 0)
Shift.create!(semester_id: 2, day: "Sunday", time: "afternoon", supervisor_id: 1, total_required_staff: 2)
Shift.create!(semester_id: 2, day: "Sunday", time: "evening", supervisor_id: 1, total_required_staff: 2)

ShiftRequest.create!(shift_id: 1, student_id: 1, requested: true, scheduled: false)
ShiftRequest.create!(shift_id: 2, student_id: 1, requested: true, scheduled: false)

ShiftRequest.create!(shift_id: 3, student_id: 2, requested: true, scheduled: false)
ShiftRequest.create!(shift_id: 4, student_id: 2, requested: true, scheduled: false)
