Supervisor.create!(first_name: "Sarah", last_name: "Baranski", email: "sarah@test.com", phone_number: "555-555-3242", password: "password")
Supervisor.create!(first_name: "Kevin", last_name: "Tracy", email: "kdawg@test.com", phone_number: "555-555-2957", password: "password")

Position.create!(title: "Equipment Facilitator", current_pay: 12, previous_pay: 12)
Position.create!(title: "Equipment Supervisor", current_pay: 12.50, previous_pay: 12)
Position.create!(title: "Shift Lead", current_pay: 13, previous_pay: 12)

Student.create!(first_name: "Anna", last_name: "Wong", email: "anna@test.com", phone_number: "555-5557896", password: "password", requested_hours: 20, position_id: 3)
Student.create!(first_name: "Rachel", last_name: "Baranski", email: "rachel@test.com", phone_number: "555-5553456", password: "password", requested_hours: 15, position_id: 2)
Student.create!(first_name: "Ryan", last_name: "Chapman", email: "ryan@test.com", phone_number: "555-555-4893", password: "password", requested_hours: 18, position_id: 1)

Semester.create!(supervisor_id: 1, start_date: DateTime.new(2020, 9, 1), end_date: DateTime.new(2020, 12, 16))
Semester.create!(supervisor_id: 2, start_date: DateTime.new(2021, 1, 11), end_date: DateTime.new(2021, 5, 1))

Shift.create!(student_id: 1, semester_id: 1, day: "Monday", time: "morning", requested: true, supervisor_id: 1, scheduled: false, total_required_staff: 2)
Shift.create!(student_id: 1, semester_id: 1, day: "Monday", time: "afternoon", requested: false, supervisor_id: 1, scheduled: false, total_required_staff: 2)
Shift.create!(student_id: 1, semester_id: 1, day: "Monday", time: "evening", requested: false, supervisor_id: 1, scheduled: false, total_required_staff: 1)
Shift.create!(student_id: 1, semester_id: 1, day: "Tuesday", time: "morning", requested: false, supervisor_id: 1, scheduled: false, total_required_staff: 2)
Shift.create!(student_id: 1, semester_id: 1, day: "Tuesday", time: "afternoon", requested: false, supervisor_id: 1, scheduled: false, total_required_staff: 2)
Shift.create!(student_id: 1, semester_id: 1, day: "Tuesday", time: "evening", requested: true, supervisor_id: 1, scheduled: true, total_required_staff: 1)
Shift.create!(student_id: 1, semester_id: 1, day: "Wednesday", time: "morning", requested: false, supervisor_id: 1, scheduled: false, total_required_staff: 2)
Shift.create!(student_id: 1, semester_id: 1, day: "Wednesday", time: "afternoon", requested: true, supervisor_id: 1, scheduled: false, total_required_staff: 2)
Shift.create!(student_id: 1, semester_id: 1, day: "Wednesday", time: "evening", requested: true, supervisor_id: 1, scheduled: true, total_required_staff: 1)
Shift.create!(student_id: 1, semester_id: 1, day: "Thursday", time: "morning", requested: false, supervisor_id: 1, scheduled: false, total_required_staff: 2)
Shift.create!(student_id: 1, semester_id: 1, day: "Thursday", time: "afternoon", requested: false, supervisor_id: 1, scheduled: false, total_required_staff: 2)
Shift.create!(student_id: 1, semester_id: 1, day: "Thursday", time: "evening", requested: false, supervisor_id: 1, scheduled: false, total_required_staff: 1)
Shift.create!(student_id: 1, semester_id: 1, day: "Friday", time: "morning", requested: true, supervisor_id: 1, scheduled: true, total_required_staff: 2)
Shift.create!(student_id: 1, semester_id: 1, day: "Friday", time: "afternoon", requested: false, supervisor_id: 1, scheduled: false, total_required_staff: 2)
Shift.create!(student_id: 1, semester_id: 1, day: "Friday", time: "evening", requested: false, supervisor_id: 1, scheduled: false, total_required_staff: 0)
Shift.create!(student_id: 1, semester_id: 1, day: "Saturday", time: "morning", requested: false, supervisor_id: 1, scheduled: false, total_required_staff: 0)
Shift.create!(student_id: 1, semester_id: 1, day: "Saturday", time: "afternoon", requested: false, supervisor_id: 1, scheduled: false, total_required_staff: 2)
Shift.create!(student_id: 1, semester_id: 1, day: "Saturday", time: "evening", requested: true, supervisor_id: 1, scheduled: true, total_required_staff: 1)
Shift.create!(student_id: 1, semester_id: 1, day: "Sunday", time: "morning", requested: false, supervisor_id: 1, scheduled: false, total_required_staff: 0)
Shift.create!(student_id: 1, semester_id: 1, day: "Sunday", time: "afternoon", requested: true, supervisor_id: 1, scheduled: true, total_required_staff: 2)
Shift.create!(student_id: 1, semester_id: 1, day: "Sunday", time: "evening", requested: false, supervisor_id: 1, scheduled: false, total_required_staff: 2)
Shift.create!(student_id: 2, semester_id: 1, day: "Monday", time: "morning", requested: false, supervisor_id: 2, scheduled: false, total_required_staff: 2)
Shift.create!(student_id: 2, semester_id: 1, day: "Monday", time: "afternoon", requested: false, supervisor_id: 2, scheduled: false, total_required_staff: 2)
Shift.create!(student_id: 2, semester_id: 1, day: "Monday", time: "evening", requested: false, supervisor_id: 2, scheduled: false, total_required_staff: 1)
Shift.create!(student_id: 2, semester_id: 1, day: "Tuesday", time: "morning", requested: false, supervisor_id: 2, scheduled: false, total_required_staff: 2)
Shift.create!(student_id: 2, semester_id: 1, day: "Tuesday", time: "afternoon", requested: true, supervisor_id: 2, scheduled: true, total_required_staff: 2)
Shift.create!(student_id: 2, semester_id: 1, day: "Tuesday", time: "evening", requested: false, supervisor_id: 2, scheduled: false, total_required_staff: 1)
Shift.create!(student_id: 2, semester_id: 1, day: "Wednesday", time: "morning", requested: false, supervisor_id: 2, scheduled: false, total_required_staff: 2)
Shift.create!(student_id: 2, semester_id: 1, day: "Wednesday", time: "afternoon", requested: false, supervisor_id: 2, scheduled: false, total_required_staff: 2)
Shift.create!(student_id: 2, semester_id: 1, day: "Wednesday", time: "evening", requested: false, supervisor_id: 2, scheduled: false, total_required_staff: 1)
Shift.create!(student_id: 2, semester_id: 1, day: "Thursday", time: "morning", requested: false, supervisor_id: 2, scheduled: false, total_required_staff: 2)
Shift.create!(student_id: 2, semester_id: 1, day: "Thursday", time: "afternoon", requested: true, supervisor_id: 2, scheduled: true, total_required_staff: 2)
Shift.create!(student_id: 2, semester_id: 1, day: "Thursday", time: "evening", requested: true, supervisor_id: 2, scheduled: true, total_required_staff: 1)
Shift.create!(student_id: 2, semester_id: 1, day: "Friday", time: "morning", requested: true, supervisor_id: 2, scheduled: false, total_required_staff: 2)
Shift.create!(student_id: 2, semester_id: 1, day: "Friday", time: "afternoon", requested: false, supervisor_id: 2, scheduled: false, total_required_staff: 2)
Shift.create!(student_id: 2, semester_id: 1, day: "Friday", time: "evening", requested: false, supervisor_id: 2, scheduled: false, total_required_staff: 0)
Shift.create!(student_id: 2, semester_id: 1, day: "Saturday", time: "morning", requested: false, supervisor_id: 2, scheduled: false, total_required_staff: 0)
Shift.create!(student_id: 2, semester_id: 1, day: "Saturday", time: "afternoon", requested: true, supervisor_id: 2, scheduled: true, total_required_staff: 2)
Shift.create!(student_id: 2, semester_id: 1, day: "Saturday", time: "evening", requested: false, supervisor_id: 2, scheduled: false, total_required_staff: 1)
Shift.create!(student_id: 2, semester_id: 1, day: "Sunday", time: "morning", requested: false, supervisor_id: 2, scheduled: false, total_required_staff: 0)
Shift.create!(student_id: 2, semester_id: 1, day: "Sunday", time: "afternoon", requested: false, supervisor_id: 2, scheduled: false, total_required_staff: 2)
Shift.create!(student_id: 2, semester_id: 1, day: "Sunday", time: "evening", requested: false, supervisor_id: 2, scheduled: false, total_required_staff: 2)
Shift.create!(student_id: 3, semester_id: 1, day: "Monday", time: "morning", requested: true, supervisor_id: 2, scheduled: true, total_required_staff: 2)
Shift.create!(student_id: 3, semester_id: 1, day: "Monday", time: "afternoon", requested: false, supervisor_id: 2, scheduled: false, total_required_staff: 2)
Shift.create!(student_id: 3, semester_id: 1, day: "Monday", time: "evening", requested: false, supervisor_id: 2, scheduled: false, total_required_staff: 1)
Shift.create!(student_id: 3, semester_id: 1, day: "Tuesday", time: "morning", requested: true, supervisor_id: 2, scheduled: true, total_required_staff: 2)
Shift.create!(student_id: 3, semester_id: 1, day: "Tuesday", time: "afternoon", requested: false, supervisor_id: 2, scheduled: false, total_required_staff: 2)
Shift.create!(student_id: 3, semester_id: 1, day: "Tuesday", time: "evening", requested: true, supervisor_id: 2, scheduled: true, total_required_staff: 1)
Shift.create!(student_id: 3, semester_id: 1, day: "Wednesday", time: "morning", requested: false, supervisor_id: 2, scheduled: false, total_required_staff: 2)
Shift.create!(student_id: 3, semester_id: 1, day: "Wednesday", time: "afternoon", requested: false, supervisor_id: 2, scheduled: false, total_required_staff: 2)
Shift.create!(student_id: 3, semester_id: 1, day: "Wednesday", time: "evening", requested: true, supervisor_id: 2, scheduled: true, total_required_staff: 1)
Shift.create!(student_id: 3, semester_id: 1, day: "Thursday", time: "morning", requested: false, supervisor_id: 2, scheduled: false, total_required_staff: 2)
Shift.create!(student_id: 3, semester_id: 1, day: "Thursday", time: "afternoon", requested: true, supervisor_id: 2, scheduled: true, total_required_staff: 2)
Shift.create!(student_id: 3, semester_id: 1, day: "Thursday", time: "evening", requested: true, supervisor_id: 2, scheduled: true, total_required_staff: 1)
Shift.create!(student_id: 3, semester_id: 1, day: "Friday", time: "morning", requested: true, supervisor_id: 2, scheduled: true, total_required_staff: 2)
Shift.create!(student_id: 3, semester_id: 1, day: "Friday", time: "afternoon", requested: false, supervisor_id: 2, scheduled: false, total_required_staff: 2)
Shift.create!(student_id: 3, semester_id: 1, day: "Friday", time: "evening", requested: false, supervisor_id: 2, scheduled: false, total_required_staff: 0)
Shift.create!(student_id: 3, semester_id: 1, day: "Saturday", time: "morning", requested: false, supervisor_id: 2, scheduled: false, total_required_staff: 0)
Shift.create!(student_id: 3, semester_id: 1, day: "Saturday", time: "afternoon", requested: true, supervisor_id: 2, scheduled: true, total_required_staff: 2)
Shift.create!(student_id: 3, semester_id: 1, day: "Saturday", time: "evening", requested: false, supervisor_id: 2, scheduled: false, total_required_staff: 1)
Shift.create!(student_id: 3, semester_id: 1, day: "Sunday", time: "morning", requested: false, supervisor_id: 2, scheduled: false, total_required_staff: 0)
Shift.create!(student_id: 3, semester_id: 1, day: "Sunday", time: "afternoon", requested: true, supervisor_id: 2, scheduled: true, total_required_staff: 2)
Shift.create!(student_id: 3, semester_id: 1, day: "Sunday", time: "evening", requested: true, supervisor_id: 2, scheduled: true, total_required_staff: 2)
